_wandb:
    value:
        cli_version: 0.24.2
        e:
            qkszrt5lupuxblhcc5yi34546dqzq54w:
                args:
                    - --config
                    - configs/v1.yaml
                    - --modal
                    - anysolev1
                    - --device
                    - cuda
                    - --wandb_mode
                    - online
                    - --wandb_project
                    - Anysole
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "942910771200"
                        used: "689976086528"
                email: davyfangyuxuan@gmail.com
                executable: /data/fangyuxuan/miniconda3/envs/touch_gait/bin/python
                git:
                    commit: d38e47f4f747c91b0b4511864076ce8bafd9cd92
                    remote: https://github.com/DavyFangyx/AnySole.git
                gpu: NVIDIA L40
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-5872ff13-25e8-07fc-c5de-82c65ac8c39f
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-4dd71ce6-7d6c-9506-850f-0467b81d2c05
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-00581309-02b6-f36c-f6ff-f0afd57d4eeb
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-1ad39b4d-eb03-6390-4468-86134c48e40e
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-eaf3564f-3e9c-d155-097f-e03e83b856f4
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-ea1e8fa8-b05d-79e5-8ba7-25408e0220fa
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-62ec43d5-bd62-761e-d54c-9fa8191dac41
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40
                      uuid: GPU-e7d422a0-99e8-6041-30a0-e6ffb5a01144
                host: ubuntu-4U-GPU-Server
                memory:
                    total: "1081814532096"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.17
                program: -m anysole.train
                python: CPython 3.8.20
                root: /data/fangyuxuan/projects/gait
                startedAt: "2026-09-12T19:31:25.377813Z"
                writerId: qkszrt5lupuxblhcc5yi34546dqzq54w
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.8.20
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 256
cache_root:
    value: /data/fangyuxuan/projects/gait/AnysoleWorkspace/derived/AnySole/hrnet_cache/cam3
cam_id:
    value: 3
config_probs:
    value:
        - 0.5
        - 0.25
        - 0.25
d_model:
    value: 256
diffusion_sample_steps:
    value: 50
diffusion_train_steps:
    value: 1000
epochs:
    value: 200
lambda_con:
    value: 0.1
lambda_kp:
    value: 1
lambda_pose:
    value: 1
lambda_traj:
    value: 1
lambda_trec:
    value: 0.1
lambda_vrec:
    value: 0.1
lr:
    value: 0.001
modal:
    value: anysolev1
num_workers:
    value: 4
out_dir:
    value: /data/fangyuxuan/projects/gait/AnySole/outputs/v1
seq_root:
    value: /data/fangyuxuan/projects/gait/AnysoleWorkspace/derived/MotionPRO/sequences/cam3
split_csv:
    value: /data/fangyuxuan/projects/gait/AnysoleWorkspace/splits/default/splits.csv
template_path:
    value: /data/fangyuxuan/projects/gait/AnysoleWorkspace/calibration/insole_templates.json
traj_delta_w:
    value: 1
traj_delta_weight_power:
    value: 1
traj_deltas:
    value:
        - 2
        - 4
        - 8
        - 19
traj_velocity_w:
    value: 1
tw:
    value: 20
use_insole_drift:
    value: false
wandb_entity:
    value: davyfangyuxuan-nanjing-university-of-aeronautics-and-ast
wandb_eval_interval:
    value: 5
wandb_mode:
    value: online
wandb_project:
    value: Anysole
