#!/usr/bin/env python3
"""补发 ρ 网格缺失 cell 的 queue conf（恢复用；幂等，可重复执行）。

读 results/experiments/rho_grid_eval/<model>/grid_metrics_<split>.json（val 另并
canonical grid_metrics.json），对指标缺失的 (split, seed, rhoV, rhoT) 重发 conf；
指标已存在的 cell 不再入队。用于合并竞态丢 cell 或 conf 文件丢失后的补跑——配合
rho_grid.py 的「reuse 需产物+指标齐备」条件，重跑会自动补推理缺失 cell。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from configs.tools.common import model_root, load_registry  # noqa: E402

from common import EXPERIMENTS, QUEUE_DIR, _next_sequence


def load_cells(root: Path, split: str) -> dict:
    """读一个 split 的全部 cell 指标；val 额外并 canonical grid_metrics.json。"""
    cells: dict = {}
    paths = [root / ("grid_metrics_%s.json" % split)]
    if split == "val":
        paths.append(root / "grid_metrics.json")
    for path in paths:
        if not path.is_file():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        for seed_key, seed_cells in (data.get("cells") or {}).items():
            cells.setdefault(seed_key, {}).update(seed_cells)
    return cells


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--models", default="",
                        help="comma-separated model IDs（默认 registry 声明的主线）")
    args = parser.parse_args()
    registry = load_registry()
    spec = EXPERIMENTS["rho_grid_eval"]
    rhos = [int(x) for x in str(spec["RHOS"]).split(",")]
    train_rhos = [int(x) for x in str(spec["TRAIN_REPR_RHOS"]).split(",")]
    val_seeds = [int(x) for x in str(spec["VAL_SEEDS"]).split(",")]
    test_seeds = [int(x) for x in str(spec["TEST_SEEDS"]).split(",")]
    selected = [x.strip() for x in args.models.split(",") if x.strip()]
    models = selected or [str(x) for x in spec["MODEL_IDS"]]

    sequence = _next_sequence()
    total = 0
    for model_id in models:
        root = model_root(registry, "rho_grid_eval", model_id)
        if not root.is_dir():
            print("skip %s：产物目录缺失 %s（先跑 z_gen/rho_grid_eval.py 生成任务）"
                  % (model_id, root))
            continue
        missing = []
        for split, split_rhos, seeds in (
            ("train", train_rhos, [0]),
            ("val", rhos, val_seeds),
            ("test", rhos, test_seeds),
        ):
            have = load_cells(root, split)
            for seed in seeds:
                for rV in split_rhos:
                    for rT in split_rhos:
                        if "rhoV%d_rhoT%d" % (rV, rT) not in have.get("s%d" % seed, {}):
                            missing.append((split, seed, rV, rT))
        QUEUE_DIR.mkdir(parents=True, exist_ok=True)
        for split, seed, rV, rT in missing:
            suffix = "%s__%s__s%d__rhoV%d__rhoT%d" % (model_id, split, seed, rV, rT)
            path = QUEUE_DIR / ("%05d__rho_grid_eval__%s.conf" % (sequence, suffix))
            path.write_text(
                "# Generated by configs/z_gen/recover_missing_cells.py\n"
                "EXPERIMENT_ID=rho_grid_eval\n"
                "TASK=rho_grid\n"
                "MODEL_ID=%s\n"
                "GRID_SPLIT=%s\n"
                "GRID_SEED=%d\n"
                "RHO_V=%d\n"
                "RHO_T=%d\n"
                "FORCE=false\n" % (model_id, split, seed, rV, rT),
                encoding="utf-8",
            )
            print("[queue] %s" % path.name)
            sequence += 1
            total += 1
    print("emitted %d missing cell conf(s)" % total)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
